### ISSUE TITLE
Visualizer widget not available in the Widgets area anymore and is causing an error in the console

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#1156]
### Description

Visualizer widget not available in the Widgets area anymore and is causing an error in the console

### Step-by-step reproduction instructions

Go to Appearance > Widgets or go to Appearance > Customize for a theme that has widget areas registered => The Visualizer widget is no longer available, and an error appears in the console

### Screenshots, screen recording, code snippet or Help Scout ticket

![Screenshot on 2024-05-22 at 19-10-54](https://github.com/Codeinwp/visualizer/assets/3266155/c33c3165-6b11-43aa-a9e5-d48e40a21ddc)
![Screenshot on 2024-05-22 at 19-11-16](https://github.com/Codeinwp/visualizer/assets/3266155/1da3ada2-e822-4796-a1f4-2b7b97847c86)

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
This was fixed @rodica-andronache, thank you for reporting.

**Comment by rodica-andronache** [comment]
@vytisbulkevicius thank you for the fix! But for me, the error still appears in the Customizer. 

Appearance > Widgets ->Now works well
Appearance > Customize for a theme that has widget areas registered -> Still not working

**Comment by vytisbulkevicius** [comment]
Hi @preda-bogdan,

Indeed, in Customizer it still happens:
<img width="591" alt="image" src="https://github.com/Codeinwp/visualizer/assets/36594177/a8a885f2-5853-4eed-89c5-c13a1c0802b9">

**Comment by preda-bogdan** [comment]
@vytisbulkevicius
cc: @rodica-andronache 

This should be solved now, I missed checking for the Customizer.
