### ISSUE TITLE
Table chart: Unable to format using ICU pattern formatters

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#283]
ref: https://secure.helpscout.net/conversation/623333008/166051

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/visualizer/pull/284

@Vishakha-Patel FYI

**Comment by rodica-andronache** [comment]
@contactashish13 I tried this with the default table chart, and for me, it's working for all columns except the first one. Could you please check ? https://prnt.sc/kb6ysc

**Comment by contactashish13** [comment]
@rodica-andronache fixed this.

**Comment by rodica-andronache** [comment]
@contactashish13 it was working with the default chart, but after that, I tried editing the chart manually, and I removed the latest column.
After that, the settings with the dollar sign disappeared, and after I tried adding them back , all the chart broke https://prnt.sc/kcoyme and I have a console error Cannot read property type of undefined in render.js

**Comment by contactashish13** [comment]
@rodica-andronache I have fixed this but I'm not sure if your approach was the same as mine. 

My steps to reproduce the error were: manual edit, remove the column, show chart, save the chart.

A video might be more helpful if this is not able to fix the problem.

PR: https://github.com/Codeinwp/visualizer/pull/287

**Comment by rodica-andronache** [comment]
@contactashish13 yes, that was my approach too, and with that case, the problem is solved now.
But the problem is still there for the case where you remove another column, not the last one. 
For example, here I had three columns, https://prnt.sc/kdokkk, I removed the middle one, and after that, the dollar signs disappeared from the last column.

**Comment by contactashish13** [comment]
@rodica-andronache that would be an issue with any chart. Everything is tied to the column index so if a column disappears, this will happen. You need to edit the chart and add it to the correct series.

**Comment by rodica-andronache** [comment]
@contactashish13 you can't edit the last column anymore https://prnt.sc/kdq0mj

**Comment by contactashish13** [comment]
@rodica-andronache can you please share a video of what caused this?

**Comment by rodica-andronache** [comment]
@contactashish13 is the same scenario I was talking about before.
For example, here I had three columns, https://prnt.sc/kdokkk, I removed the middle one, and after that, the dollar signs disappeared from the last column.
When trying to edit the chart, the last column is not editable anymore.
Let me know if you still need the video

**Comment by contactashish13** [comment]
@rodica-andronache Yes, please share the video. I think even minor steps are important to replicate the issue.

**Comment by contactashish13** [comment]
@rodica-andronache I think the problem is with the way you delete the data and also try to delete the column type. When you delete the column type, you will see in the video it becomes a "string" and the columns shift to the left. Therefore the last column becomes a string type and there is obviously no formatting for strings. 

BTW most people will delete the column like they do in a spreadsheet - select the column and delete - instead of deleting each row one by one. The column type remains what it was (number) and when they save the chart, its all okay.

**Comment by rodica-andronache** [comment]
you're right, everything is ok 👍
